spring:
  application:
    name: java-challange
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://app:apppassword@localhost:27017}
      database: applications

mongock:
  migration-scan-package: com.vmogroup.java_challange.changelog
  mongo-uri: ${MONGOCK_URI:mongodb://mongock:password@localhost:27017}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: "/actuator"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{26} - %msg %ex{10}%n"


